### ISSUE TITLE
vlsingle - service is not restarted on change to service file

### ISSUE THREAD

**Issue by ShaunDwyer** [VictoriaMetrics/ansible-playbooks#75]
When updates to /etc/systemd/system/victorialogs.service are made, the hander for restarting the service does not fire.

I updated some options that resulted in some additional command line parameters in the service file.
I expected that the handler would fire to restart the service, but it doesn't.

In roles/vlsingle/tasks/configure.yaml:

```
- name: Copy VictoriaMetrics systemd unit file
  ansible.builtin.template:
    src: victorialogs.service.j2
    dest: /etc/systemd/system/victorialogs.service
    owner: root
    group: root
    mode: 0644
  register: config_template
  no_log: True

- name: Daemon-reload VictoriaMetrics service
  become: true
  notify: Restart VictoriaLogs service
  ansible.builtin.systemd:
    daemon_reload: true
    name: victorialogs
  when: config_template is changed  # noqa: no-handler
```

The daemon-reload task evaluates to "ok" when run, and never fires the handler:

```
TASK [victoriametrics.cluster.vlsingle : Copy VictoriaMetrics systemd unit file] ************************************************************************************************************
changed: [victorialogs]

TASK [victoriametrics.cluster.vlsingle : Daemon-reload VictoriaMetrics service] *************************************************************************************************************
ok: [victorialogs]
```
